spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        missing-queues-fatal: false
        auto-startup: true

server:
  port: 8083

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
